name: CI-CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Login to AWS ECR (optional if you need AWS image)
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region us-west-2

      - name: Build Docker Image
        run: |
          docker build -t cicd-builder -f docker/Dockerfile .

      - name: Run Makefile tasks inside Docker
        run: |
          docker run -v $PWD:/working cicd-builder bash -c "make validate && make plan"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Infrastructure to Azure
        run: |
          docker run -v $PWD:/working cicd-builder bash -c "make deploy"

      - name: Publish Docker Image to Azure Container Registry
        run: |
          az acr login --name ${{ secrets.AZURE_ACR_NAME }}
          docker tag cicd-builder ${{ secrets.AZURE_ACR_NAME }}.azurecr.io/cicd-builder:latest
          docker push ${{ secrets.AZURE_ACR_NAME }}.azurecr.io/cicd-builder:latest
